Front page logic
cs-24-sw-2-14/MagicBoard pull request #33
Opened 2024-04-09 09:08 UTC by elmavukicevic

we cnat do no more bbruh

vi mangler backend logikken ++++++++ side 2 efter man har input username ! nice(-marc)

2024-04-09 13:12 UTC, krestenlaust reviewed
Der sker ikke så meget, det eneste jeg har at sige er at jeg tror der skal køres en formatter

2024-04-10 07:24 UTC, Many5900 requested changes

2024-04-10 07:24 UTC, Many5900 commented on src/app.css
> +}
```suggestion

```

2024-04-10 07:25 UTC, Many5900 commented on src/app.css
> +}
Det bruges ikke længere, efter at vi manuelt importerede det med et <link>-tag

2024-04-11 09:03 UTC, Many5900 approved these changes
LGMT!

2024-04-11 09:03 UTC, merged