UI dexist
cs-24-sw-2-14/MagicBoard pull request #59
Opened 2024-04-18 12:00 UTC by tbdlarsen

function to check if board already exists in backend api endpoint (endpoint doesnt work yet).
a box underneath input field changes color depending on whether the board exists or not

2024-04-18 12:02 UTC, Many5900 commented
Kunne du ikke komme op med et mere sigende navn end "UI dexist"? Hvad skal det overhovedet betyde?

2024-04-18 12:04 UTC, Many5900 commented on src/lib/components/FrontPage.svelte
> +
Hvad gør de ekstra linjer?

2024-04-18 12:05 UTC, Many5900 commented on src/lib/components/FrontPage.svelte
> +
Hvad gør den ekstra linje?

2024-04-18 12:06 UTC, Many5900 commented on src/lib/components/FrontPage.svelte
> +
Hvad gør det ekstra linjer?

2024-04-18 12:07 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +
https://esolangs.org/wiki/Whitespace

2024-04-18 12:08 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +
De kunne gøre meget, jeg ser bare spild af potentiale

2024-04-18 12:11 UTC, krestenlaust requested changes
Til den det måtte vedkomme

2024-04-18 12:11 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +  let color:string;
Hvad gør manglen på mellemrum mellem typen og identifying factor her?
```suggestion
  let color: string;
```

2024-04-18 12:11 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
>  	let inputfield: string = '';
```suggestion
	let inputfield: string = "";
```

2024-04-18 12:11 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +    }
Hej Thorbjørn,

Har du overvejet følgende?
```suggestion
    color = boardExists() === true ? "green-500" : "red-500";
```

2024-04-18 12:11 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +        const response = await fetch(`https://64.227.121.226:1337/v1/board/czech_uid`);
Hej igen,

Har du overvejet at ikke hardcode følgende værdi?

Venlig hilsen
Kresten

2024-04-18 12:12 UTC, tbdlarsen commented on src/lib/components/FrontPage.svelte
> +  let color:string;
ingenting

2024-04-18 12:13 UTC, Many5900 commented on src/lib/components/FrontPage.svelte
> +			color = 'red-500';
```suggestion
			color = "green-500";
		} else {
			color = "red-500";
```

2024-04-18 12:14 UTC, Many5900 commented on src/lib/components/FrontPage.svelte
> +			const response = await fetch(`https://64.227.121.226:1337/v1/board/czech_uid`);
Mangler du ikke at skrive id som parameter?

2024-04-18 12:29 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +  let color:string;
okay tak

2024-04-18 12:30 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +			color = 'red-500';
wow

2024-04-18 12:30 UTC, krestenlaust commented on src/lib/components/FrontPage.svelte
> +			const response = await fetch(`https://64.227.121.226:1337/v1/board/czech_uid`);
godt fanget, 2602

2024-04-18 12:49 UTC, krestenlaust approved these changes
Gutchi

2024-04-23 07:58 UTC, krestenlaust commented
*You may merge when ready*

nvm

2024-04-25 10:10 UTC, krestenlaust approved these changes
Ser stadig fornuftigt ud

2024-04-25 10:32 UTC, merged